export type JobType = {
    id: number,
    tenant_id: string,
    type: string,
    status: string,
    payload_order_id: number,
    payload_status: string,
    destination_url: string,
    destination_method: string,
    destination_headers: string,
    destination_timeout_ms: string,
    dedupe_key: string,
    execute_at: string,
    created_at: string,
    updated_at: string,
    max_attempts: number,
    current_attempts: number,
    base_delay_ms: number,
    max_delay_ms: number,
    rate_limit_rps: number,
    rate_limit_burst: number,
    last_error: string,
    idempotency_key: number,
}